use crate::moves::Move;
use std::collections::HashMap;
use std::sync::OnceLock;

/// Opening book entry: position hash -> best UCI move.
/// Generated by engine analysis at depth 10-16 with 8 threads.
/// Extended with deep solving analysis (depth 12-14) proving forced mate
/// for White after 1. e3 in all major lines.
const BOOK_DATA: &[(u64, &str)] = &[
    // ================================================================
    // === Startpos ===
    // ================================================================
    (0xe78ab28da0cff36f, "e2e3"),   // startpos → 1. e3

    // ================================================================
    // === Black responses to 1. e3 (complete coverage) ===
    // ================================================================
    (0x3549914d396bcd7c, "e7e6"),   // 1. e3 → 1...e6 (best defense)
    (0x802a71bf90b920ac, "d1g4"),   // 1. e3 e5 → 2. Qg4
    (0xe2b39ad04bda8dcf, "d1f3"),   // 1. e3 c5 → 2. Qf3
    (0xe577c7d748b33c37, "f1b5"),   // 1. e3 d5 → 2. Bb5 (mate)
    (0x9504fcb9edf890a1, "f1b5"),   // 1. e3 d6 → 2. Bb5 (mate)
    (0x69c56371582d78b0, "d1f3"),   // 1. e3 Nf6 → 2. Qf3 (mate)
    (0x811de30068156c64, "d1f3"),   // 1. e3 Nc6 → 2. Qf3 (mate)
    (0x175b837b4c186548, "d1f3"),   // 1. e3 c6 → 2. Qf3
    (0xb9b180d1ff388987, "b1c3"),   // 1. e3 a6 → 2. Nc3 (mate)
    (0xac8cf01423b0ee77, "b1a3"),   // 1. e3 b6 → 2. Na3
    (0x1096c64dcf912bc5, "b1c3"),   // 1. e3 h6 → 2. Nc3
    (0xb15baea501175283, "d1h5"),   // 1. e3 g6 → 2. Qh5
    (0x21f3225a96ea0efd, "d1h5"),   // 1. e3 f6 → 2. Qh5 (mate)
    (0x4a7b6cd044d36ece, "d1h5"),   // 1. e3 f5 → 2. Qh5 (mate)
    // New first-move responses:
    (0x3eb9976bbb8190ba, "b1c3"),   // 1. e3 a5 → 2. Nc3
    (0x6b5e2b24167f6a38, "b1c3"),   // 1. e3 b5 → 2. Nc3
    (0x9e0ec3c798b22cb0, "b1c3"),   // 1. e3 g5 → 2. Nc3 (mate)
    (0x0b3f3e78e580f3ca, "b1c3"),   // 1. e3 h5 → 2. Nc3
    (0x0ab27cb1d5a016fa, "d1f3"),   // 1. e3 Na6 → 2. Qf3
    (0x6659657f1b2273aa, "b1c3"),   // 1. e3 Nh6 → 2. Nc3 (mate)

    // ================================================================
    // === 1. e3 e6 main line ===
    // ================================================================
    (0x332a1d56735ffee3, "d1e2"),   // 1. e3 e6 → 2. Qe2
    (0xcd1207ee24ef0001, "b7b6"),   // 1. e3 e6 2. Qe2 → 2...b6

    // ================================================================
    // === 2. Qe2 — White vs all Black responses ===
    // ================================================================
    (0x54d766b73e34230a, "e2b5"),   // 2. Qe2 b6 → 3. Qb5
    (0x26d421e2f377951b, "e2d3"),   // 2. Qe2 Bb4 → 3. Qd3
    (0x1d2c51745537f14a, "e2b5"),   // 2. Qe2 d5 → 3. Qb5 (mate: diagonal b5-c6-d7-e8)
    (0x6d5f6a1af07c5ddc, "e2b5"),   // 2. Qe2 d6 → 3. Qb5 (mate: d7 vacated)
    (0xb220fa735957a3b3, "e2h5"),   // 2. Qe2 f5 → 3. Qh5 (mate: f7 vacated)
    (0x794675a37591a119, "e2f3"),   // 2. Qe2 Nc6 → 3. Qf3 (mate)
    (0xbc2af087546476e8, "e2f3"),   // 2. Qe2 Qf6 → 3. Qf3 (mate)
    (0x586fc256eb471a62, "e2b5"),   // 2. Qe2 Qe7 → 3. Qb5
    (0x1ae80c73565e40b2, "e2b5"),   // 2. Qe2 c5 → 3. Qb5
    (0x919ef5d245a9b5cd, "e2d3"),   // 2. Qe2 Nf6 → 3. Qd3
    (0x41ea1672e2bc44fa, "e2d3"),   // 2. Qe2 a6 → 3. Qd3
    (0xe8cd50eed215e6b8, "e2a6"),   // 2. Qe2 h6 → 3. Qa6
    (0xef0015d8519ca835, "e2d3"),   // 2. Qe2 c6 → 3. Qd3
    (0x490038061c939ffe, "b1c3"),   // 2. Qe2 g6 → 3. Nc3
    (0xf364a8dbf8043eb7, "e2d3"),   // 2. Qe2 h5 → 3. Qd3
    (0x9305bd870bfba745, "e2d3"),   // 2. Qe2 b5 → 3. Qd3
    (0x624620e2bf3df8e0, "e2a6"),   // 2. Qe2 Bd6 → 3. Qa6
    (0xef42a7c15b038901, "e2h5"),   // 2. Qe2 Bc5 → 3. Qh5
    (0x8378b9a046058f02, "b1c3"),   // 2. Qe2 Ne7 → 3. Nc3

    // ================================================================
    // === 2. Qe2 Bb4 3. Qd3 continuations ===
    // ================================================================
    (0xf35a54b71483b4e5, "b4e7"),   // 3. Qd3 → 3...Be7
    (0xe943588497093785, "b1c3"),   // 3. Qd3 Be7 → 4. Nc3 (mate)
    (0x626ad1364f52d17d, "g1f3"),   // 3. Qd3 Bc3 → 4. Nf3 (mate)
    (0x470e26fa45fd15fd, "d3c4"),   // 3. Qd3 Nc6 → 4. Qc4 (mate)
    (0x1585de91af125dab, "d3d6"),   // 3. Qd3 Qe7 → 4. Qd6 (mate)
    (0x1c5eaec061c9dfc8, "d3d6"),   // 3. Qd3 Kf8 → 4. Qd6 (mate)
    (0x2b1b11184267d05d, "d3g6"),   // 3. Qd3 Nf6 → 4. Qg6 (mate)
    (0x2364022d655b45ae, "d3b5"),   // 3. Qd3 d5 → 4. Qb5 (mate)
    (0xf8aa52919669e923, "a2a3"),   // 3. Qd3 a5 → 4. a3
    (0xd68503b7e279525c, "b1c3"),   // 3. Qd3 h6 → 4. Nc3 (mate)
    // Extended: Be7 4. Nc3 continuation
    (0x0e6e3b24f5c30847, "e7f6"),   // 4. Nc3 → 4...Bf6 (forced mate at depth 11)

    // ================================================================
    // === 2...b6 3. Qb5 — the critical main line ===
    // === Qb5 flips b6 and d7 pawns to White ===
    // ================================================================
    (0xed67221ac4b5384f, "f8b4"),   // 3. Qb5 → 3...Bb4 (best defense)

    // --- 3. Qb5 Black alternatives (all losing) ---
    (0x0bb8a83c7f24d101, "b5g5"),   // 3...Qe7 → 4. Qg5 (+5205)
    (0xc2499fb8d1ca7eae, "b5g5"),   // 3...Nf6 → 4. Qg5 (mate)
    (0xa30d9c54a65fb74c, "b5g5"),   // 3...Ne7 → 4. Qg5 (mate)
    (0xb5f8d8b767c0f265, "b5c5"),   // 3...Bb7 → 4. Qc5 (mate)
    (0x9c5fd573b43e4ea6, "d7d8q"),  // 3...Qf6 → 4. d8=Q (mate! d7 pawn promotes)
    (0x6aef3a42665edd25, "b1c3"),   // 3...c6 → 4. Nc3 (+7555)
    (0xc40539e8d57e31ea, "b1c3"),   // 3...a6 → 4. Nc3 (+7555)
    (0xd3118d2f185e06f9, "b6b7"),   // 3...h5 → 4. b7! (+4675, advance flipped pawn)
    (0x9255df87b90d9bfd, "b1c3"),   // 3...f5 → 4. Nc3 (mate)
    (0x998e61158e3bedd1, "b5c6"),   // 3...Bc5 → 4. Qc6 (+3050)
    (0x423305165f67c0ae, "b5c5"),   // 3...Bd6 → 4. Qc5 (+3940)

    // ================================================================
    // === 3...Bb4 4. Nf3 — bishop flips d2, knight flips it back ===
    // ================================================================
    (0x06a10416132dad55, "g1f3"),   // 3...Bb4 → 4. Nf3

    // --- 4. Nf3 Black alternatives ---
    (0x06ea94d633fc1dd5, "b4f8"),   // 4. Nf3 → 4...Bf8 (best: mate proven at d13)
    (0x058e433e84d6dc75, "e1d1"),   // 4...Ba5 → 5. Kd1 (mate proven at d12)
    (0xf822ced177ab6e12, "b5c6"),   // 4...Bc5 → 5. Qc6 (mate)
    (0x97da1157682d784d, "b5d3"),   // 4...Bc3 → 5. Qd3 (mate)
    (0x1cf398e5b0769eb5, "b5h5"),   // 4...Be7 → 5. Qh5 (mate)
    (0x239faad2a6f7436d, "b5c5"),   // 4...Bd6 → 5. Qc5 (mate)
    (0xb2bee69b6282bccd, "b5c5"),   // 4...Nc6 → 5. Qc5 (mate)
    (0xe0351ef0886df49b, "b5c5"),   // 4...Qe7 → 5. Qc5 (mate)
    (0x29c4297426835b34, "b5g5"),   // 4...Nf6 → 5. Qg5 (mate)
    (0x389c3be3ef172363, "f3e5"),   // 4...h5 → 5. Ne5 (mate)
    (0x2f888f2422371470, "b1c3"),   // 4...a6 → 5. Nc3 (mate)

    // ================================================================
    // === 4...Bf8 5. Qc4 — queen flips c7 and e6 to White ===
    // === After Qc4: White pawns on b6, c7, d7, e6 surround Black king ===
    // ================================================================
    (0x234e61eb34bae708, "b5c4"),   // 4...Bf8 → 5. Qc4

    // --- 5. Qc4 Black alternatives (ALL lead to forced mate) ---
    (0xf7928e5cd3b2f67b, "a7a5"),   // 5. Qc4 → 5...a5 (best)
    (0xc9e421690f59c8cd, "b1c3"),   // 5...h5 → 6. Nc3 (mate)
    (0x5cd5dcd6726b17b7, "e6e7"),   // 5...g5 → 6. e7! (flipped pawn advances, mate)
    (0xecd1b1a1c3e51c48, "f3e5"),   // 5...Qe7 → 6. Ne5 (mate)
    (0x1c54a850042a6361, "c4c3"),   // 5...Bb4 → 6. Qc3 (mate)
    (0xd8bc33fec6cdb09a, "e6e7"),   // 5...Nf6 → 6. e7! (mate)
    (0xa9bc0621743dfede, "c4c6"),   // 5...Bb7 → 6. Qc6 (mate)

    // ================================================================
    // === 5...a5 6. Nc3 — knight develops, all Black moves lose ===
    // ================================================================
    (0xfc62887a5158abbd, "b1c3"),   // 5...a5 → 6. Nc3

    // --- 6. Nc3 Black alternatives (ALL lead to forced mate) ---
    (0x1b4febda3392947f, "g7g5"),   // 6. Nc3 → 6...g5 (best: mate in 3)
    (0x0c7b2d1f614c33cd, "c4d4"),   // 6...Bd6 → 7. Qd4 (mate)
    (0x3461567826edd29e, "c3e4"),   // 6...Nf6 → 7. Ne4 (mate)
    (0x000cd42723c57e4c, "f3e5"),   // 6...Qe7 → 7. Ne5 (mate)
    (0x5525559451781b7c, "c4b4"),   // 6...Ne7 → 7. Qb4 (mate in 3)
    (0x3e90bcdac56872c6, "c3e4"),   // 6...h6 → 7. Ne4 (mate)
    (0x456163a7941d9cda, "e6e7"),   // 6...Bb7 → 7. e7! (mate in 4)
    (0x647d16474e2a37cd, "f3e5"),   // 6...f5 → 7. Ne5 (mate)
    (0x4ca7f8a8532c6eed, "c4c5"),   // 6...Bb4 → 7. Qc5 (mate)

    // ================================================================
    // === 6...g5 7. Ne4 — knight flips g5, threatens Nd6# ===
    // ================================================================
    (0xb008b950924b75b3, "c3e4"),   // 6...g5 → 7. Ne4

    // --- 7. Ne4 Black responses (almost all instant mate) ---
    (0x587e2cce9151e8a4, "c8b7"),   // 7. Ne4 → 7...Bb7 (only move surviving >1 move)
    (0x9a025599cd142176, "e4f6"),   // 7...Qe7 → 8. Nf6# (knight attacks e8)
    (0xb3b80ac246c97dbe, "e4d6"),   // 7...Bb4 → 8. Nd6# (knight attacks e8)
    (0xec2a5e83c02f49bc, "e4d6"),   // 7...Nc6 → 8. Nd6#
    (0xdfe520fbb4966c71, "e4d6"),   // 7...Na6 → 8. Nd6#
    (0xa49e3d642bb92dfc, "e4d6"),   // 7...h6 → 8. Nd6#
    (0x95fbd97372c208c4, "e4d6"),   // 7...f6 → 8. Nd6#
    (0x660883fb4dbad612, "e4d6"),   // 7...h5 → 8. Nd6#
    (0x2f56f617e7974344, "d7d8q"),  // 7...Qf6 → 8. d8=Q# (pawn promotes, attacks e8)

    // ================================================================
    // === 7...Bb7 8. Qb4 — flips a5, e4 knight, f8 bishop ===
    // === MATE IN 1: every Black reply loses to Nd6#/Qe7#/c8=Q#/Qd6# ===
    // ================================================================
    (0x2603dd8a2373d1ec, "c4b4"),   // 7...Bb7 → 8. Qb4

    // --- 8. Qb4 Black responses (all mate in 1) ---
    (0xce935275ae6cc1c0, "b8a6"),   // 8. Qb4 → 8...Na6 (all equivalent)
    (0xf7bdffb2bfd34b50, "e4d6"),   // 8...Na6 → 9. Nd6# (knight flips king)
    (0xa014e4f4eada6b97, "b4d6"),   // 8...Ke7 → 9. Qd6# (queen flips king on e7)
    (0x8003beff1b3aab28, "c7c8q"),  // 8...Qe7 → 9. c8=Q# (promotes, attacks through d8 to e8)
    (0x0316a7c84dff21a0, "b4e7"),   // 8...f6 → 9. Qe7# (queen flips king on e8)
    (0x327343df14840498, "b4e7"),   // 8...h6 → 9. Qe7#
    (0xbfe9f351e9c36604, "b4e7"),   // 8...Nf6 → 9. Qe7#

    // ================================================================
    // === 1. e3 e5 2. Qg4 line ===
    // ================================================================
    (0x7a5a39e785a0a024, "d8e7"),   // 2. Qg4 → 2...Qe7
    (0x9c85b3c13e31496a, "g4a4"),   // 2. Qg4 Qe7 → 3. Qa4
    (0xd35b4afae049c8f9, "f1e2"),   // 2. Qg4 h5 → 3. Be2
    (0x647e8de5980420f4, "d8e7"),   // 2. Qg4 h5 3. Be2 → 3...Qe7
    (0x82a107c32395c9ba, "g4a4"),   // 2. Qg4 h5 3. Be2 Qe7 → 4. Qa4
    (0xcb0e3867b07a0afb, "e7d6"),   // 4. Qa4 → 4...Bd6

    // === 1. e3 e5 2. Qg4 Qe7 3. Qa4 Black's 3rd ===
    (0x749a64ca10aae61c, "a4h4"),   // 3. Qa4 Kd8 → 4. Qh4
    (0x2832ebbbc51bc49b, "d7d8q"),  // 3. Qa4 Nc6 → d8=Q (mate)
    (0x7567e191794dd7f6, "a4d7"),   // 3. Qa4 d6 → 4. Qd7 (mate)

    // ================================================================
    // === 1. e3 c5 sideline ===
    // ================================================================
    (0x296cbc59ec26458e, "g7g5"),   // 1. e3 c5 2. Qf3 → 2...g5
    (0x2f0f3042a6127611, "f3d5"),   // 1. e3 c5 2. Qf3 e6 → 3. Qd5 (mate)
    (0x11c00da1668a0f04, "e7e6"),   // 1. e3 c5 2. c3 → 2...e6
    (0x1a300b87e46052c2, "d1f3"),   // 1. e3 c5 2. c3 a5 → 3. Qf3

    // ================================================================
    // === 1. Nc3 lines ===
    // ================================================================
    (0x00a7d12dc205ccad, "e7e6"),   // 1. Nc3 → 1...e6
    (0x06c45d368831ff32, "d2d4"),   // 1. Nc3 e6 → 2. d4
    (0x6472bdd525869415, "d7d5"),   // 1. Nc3 e6 2. d4 → 2...d5
    (0xb44ceb4f545e655e, "b2b4"),   // 1. Nc3 e6 2. d4 d5 → 3. b4
    (0xd4077ef61195c121, "d8f6"),   // 1. Nc3 e6 2. e3 → 2...Qf6 (mate)
    (0xb5c431df6bd7217d, "e2e3"),   // 1. Nc3 e5 → 2. e3
    (0x6707121ff2731f6e, "d8e7"),   // 1. Nc3 e5 2. e3 → 2...Qe7
    (0xf27ad7a73ddb050d, "d1e2"),   // 1. Nc3 e5 2. e3 Qe7 → 3. Qe2
    (0x2a5d032f96c66a95, "d7d6"),   // 1. Nc3 e5 2. Nb5 → 2...d6

    // ================================================================
    // === Trap lines (Black pawn promotion threats) ===
    // ================================================================
    (0x04199ef57ce902f6, "d2d1q"),  // 2. Qe2 Bb4 3. Qa6 → d1=Q (mate)
    (0xbcb6f1e60aa4ff3c, "d2d1q"),  // 2. Qe2 Bb4 3. Qf3 → d1=Q (mate)
    (0x196e27a884cbf4f6, "d2d1q"),  // 3. Qb5 Bb4 4. Qa4 → d1=Q (mate)

    // ================================================================
    // === 2...b6 3. Qa6 sideline ===
    // ================================================================
    (0xf35c3bab5b6a4457, "d8f6"),   // 2...b6 3. Qa6 → 3...Qf6
];

static BOOK: OnceLock<HashMap<u64, Move>> = OnceLock::new();

fn init_book() -> HashMap<u64, Move> {
    let mut map = HashMap::with_capacity(BOOK_DATA.len());
    for &(hash, uci) in BOOK_DATA {
        if let Some(m) = Move::from_uci(uci) {
            map.insert(hash, m);
        }
    }
    map
}

/// Look up a position in the opening book.
/// Returns the best move if the position is in the book.
pub fn probe(hash: u64) -> Option<Move> {
    let book = BOOK.get_or_init(init_book);
    book.get(&hash).copied()
}
