use crate::moves::Move;
use std::collections::HashMap;
use std::sync::OnceLock;

/// Opening book entry: position hash -> best UCI move.
/// Generated by engine analysis at depth 10-16 with 8 threads (15-45s/position).
const BOOK_DATA: &[(u64, &str)] = &[
    // === Startpos ===
    (0xe78ab28da0cff36f, "e2e3"),   // startpos → 1. e3

    // === Black responses to 1. e3 ===
    (0x3549914d396bcd7c, "e7e6"),   // 1. e3 → 1...e6 (best)
    (0x802a71bf90b920ac, "d1g4"),   // 1. e3 e5 → 2. Qg4!
    (0xe2b39ad04bda8dcf, "d1f3"),   // 1. e3 c5 → 2. Qf3
    (0xe577c7d748b33c37, "f1b5"),   // 1. e3 d5 → 2. Bb5 (mate)
    (0x69c56371582d78b0, "d1f3"),   // 1. e3 Nf6 → 2. Qf3 (mate)
    (0x811de30068156c64, "d1f3"),   // 1. e3 Nc6 → 2. Qf3 (mate)
    (0x175b837b4c186548, "d1f3"),   // 1. e3 c6 → 2. Qf3
    (0x9504fcb9edf890a1, "f1b5"),   // 1. e3 d6 → 2. Bb5 (mate)
    (0xb9b180d1ff388987, "b1c3"),   // 1. e3 a6 → 2. Nc3 (mate)
    (0xac8cf01423b0ee77, "b1a3"),   // 1. e3 b6 → 2. Na3
    (0x1096c64dcf912bc5, "b1c3"),   // 1. e3 h6 → 2. Nc3
    (0xb15baea501175283, "d1h5"),   // 1. e3 g6 → 2. Qh5
    (0x21f3225a96ea0efd, "d1h5"),   // 1. e3 f6 → 2. Qh5 (mate)
    (0x4a7b6cd044d36ece, "d1h5"),   // 1. e3 f5 → 2. Qh5 (mate)

    // === 1. e3 e6 main line ===
    (0x332a1d56735ffee3, "d1e2"),   // 1. e3 e6 → 2. Qe2
    (0xcd1207ee24ef0001, "b7b6"),   // 1. e3 e6 2. Qe2 → 2...b6

    // === White vs Black's responses to 2. Qe2 ===
    (0x26d421e2f377951b, "e2d3"),   // 2. Qe2 Bb4 → 3. Qd3
    (0x586fc256eb471a62, "e2b5"),   // 2. Qe2 Qe7 → 3. Qb5
    (0x54d766b73e34230a, "e2b5"),   // 2. Qe2 b6 → 3. Qb5
    (0x1ae80c73565e40b2, "e2b5"),   // 2. Qe2 c5 → 3. Qb5
    (0x1d2c51745537f14a, "e2b5"),   // 2. Qe2 d5 → 3. Qb5 (mate)
    (0x6d5f6a1af07c5ddc, "e2b5"),   // 2. Qe2 d6 → 3. Qb5 (mate)
    (0x919ef5d245a9b5cd, "e2d3"),   // 2. Qe2 Nf6 → 3. Qd3
    (0x794675a37591a119, "e2f3"),   // 2. Qe2 Nc6 → 3. Qf3 (mate)
    (0x41ea1672e2bc44fa, "e2d3"),   // 2. Qe2 a6 → 3. Qd3
    (0xe8cd50eed215e6b8, "e2a6"),   // 2. Qe2 h6 → 3. Qa6
    (0xb220fa735957a3b3, "e2h5"),   // 2. Qe2 f5 → 3. Qh5 (mate)
    (0xef0015d8519ca835, "e2d3"),   // 2. Qe2 c6 → 3. Qd3
    (0x490038061c939ffe, "b1c3"),   // 2. Qe2 g6 → 3. Nc3
    (0xf364a8dbf8043eb7, "e2d3"),   // 2. Qe2 h5 → 3. Qd3
    (0x9305bd870bfba745, "e2d3"),   // 2. Qe2 b5 → 3. Qd3

    // === 1. e3 e6 2. Qe2 Bb4 3. Qd3 continuations ===
    (0xf35a54b71483b4e5, "b4e7"),   // 3. Qd3 → 3...Be7
    (0xe943588497093785, "b1c3"),   // 3. Qd3 Be7 → 4. Nc3 (mate)
    (0x626ad1364f52d17d, "g1f3"),   // 3. Qd3 Bc3 → 4. Nf3 (mate)
    (0x470e26fa45fd15fd, "d3c4"),   // 3. Qd3 Nc6 → 4. Qc4 (mate)
    (0x1585de91af125dab, "d3d6"),   // 3. Qd3 Qe7 → 4. Qd6 (mate)
    (0x1c5eaec061c9dfc8, "d3d6"),   // 3. Qd3 Kf8 → 4. Qd6 (mate)

    // === 1. e3 e6 2. Qe2 b6 continuations ===
    (0xed67221ac4b5384f, "f8b4"),   // 2...b6 3. Qb5 → 3...Bb4
    (0xf35c3bab5b6a4457, "d8f6"),   // 2...b6 3. Qa6 → 3...Qf6

    // === 1. e3 e5 2. Qg4 line ===
    (0x7a5a39e785a0a024, "d8e7"),   // 2. Qg4 → 2...Qe7
    (0x9c85b3c13e31496a, "g4a4"),   // 2. Qg4 Qe7 → 3. Qa4
    (0xd35b4afae049c8f9, "f1e2"),   // 2. Qg4 h5 → 3. Be2
    (0x647e8de5980420f4, "d8e7"),   // 2. Qg4 h5 3. Be2 → 3...Qe7
    (0x82a107c32395c9ba, "g4a4"),   // 2. Qg4 h5 3. Be2 Qe7 → 4. Qa4
    (0xcb0e3867b07a0afb, "e7d6"),   // 4. Qa4 → 4...Bd6

    // === 1. e3 c5 sideline ===
    (0x296cbc59ec26458e, "g7g5"),   // 1. e3 c5 2. Qf3 → 2...g5
    (0x2f0f3042a6127611, "f3d5"),   // 1. e3 c5 2. Qf3 e6 → 3. Qd5 (mate)
    (0x11c00da1668a0f04, "e7e6"),   // 1. e3 c5 2. c3 → 2...e6
    (0x1a300b87e46052c2, "d1f3"),   // 1. e3 c5 2. c3 a5 → 3. Qf3

    // === 1. Nc3 lines ===
    (0x00a7d12dc205ccad, "e7e6"),   // 1. Nc3 → 1...e6
    (0x06c45d368831ff32, "d2d4"),   // 1. Nc3 e6 → 2. d4
    (0x6472bdd525869415, "d7d5"),   // 1. Nc3 e6 2. d4 → 2...d5
    (0xb44ceb4f545e655e, "b2b4"),   // 1. Nc3 e6 2. d4 d5 → 3. b4
    (0xd4077ef61195c121, "d8f6"),   // 1. Nc3 e6 2. e3 → 2...Qf6 (mate)
    (0xb5c431df6bd7217d, "e2e3"),   // 1. Nc3 e5 → 2. e3
    (0x6707121ff2731f6e, "d8e7"),   // 1. Nc3 e5 2. e3 → 2...Qe7
    (0xf27ad7a73ddb050d, "d1e2"),   // 1. Nc3 e5 2. e3 Qe7 → 3. Qe2
    (0x2a5d032f96c66a95, "d7d6"),   // 1. Nc3 e5 2. Nb5 → 2...d6

    // === 1. e3 e6 2. Qe2 Bb4 — Black trap lines ===
    (0x04199ef57ce902f6, "d2d1q"),  // 3. Qa6 → d1=Q (mate)
    (0xbcb6f1e60aa4ff3c, "d2d1q"), // 3. Qf3 → d1=Q (mate)
];

static BOOK: OnceLock<HashMap<u64, Move>> = OnceLock::new();

fn init_book() -> HashMap<u64, Move> {
    let mut map = HashMap::with_capacity(BOOK_DATA.len());
    for &(hash, uci) in BOOK_DATA {
        if let Some(m) = Move::from_uci(uci) {
            map.insert(hash, m);
        }
    }
    map
}

/// Look up a position in the opening book.
/// Returns the best move if the position is in the book.
pub fn probe(hash: u64) -> Option<Move> {
    let book = BOOK.get_or_init(init_book);
    book.get(&hash).copied()
}
